# Generated by Django 2.0 on 2017-12-18 10:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    replaces = [('cc', '0001_initial'), ('cc', '0002_auto_20150105_1859'), ('cc', '0003_auto_20150106_1041'), ('cc', '0004_txid_not_uniq'), ('cc', '0005_currency_dust'), ('cc', '0006_auto_20160519_1952'), ('cc', '0007_withdrawtransaction_state'), ('cc', '0008_withdrawtransaction_state'), ('cc', '0009_WT_ixid_index'), ('cc', '0010_withdrawtransaction_walletconflicts'), ('cc', '0011_auto_20171218_1001')]

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('label', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('ticker', models.CharField(default='BTC', max_length=4, primary_key=True, serialize=False, verbose_name='Ticker')),
                ('label', models.CharField(default='Bitcoin', max_length=20, unique=True, verbose_name='Label')),
                ('magicbyte', models.CharField(default='0,5', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Magicbytes')),
                ('last_block', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Last block')),
                ('api_url', models.CharField(blank=True, default='http://localhost:8332', max_length=100, null=True, verbose_name='API hostname')),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Balance')),
                ('holded', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Holded')),
                ('unconfirmed', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Unconfirmed')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('reason_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reason_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, verbose_name='Txid')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cc.Currency')),
                ('address', models.CharField(default='', max_length=50, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Balance')),
                ('holded', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Holded')),
                ('unconfirmed', models.DecimalField(decimal_places=8, default=0, max_digits=18, verbose_name='Unconfirmed')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Label')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cc.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Amount')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('txid', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Txid')),
                ('fee', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Fee')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cc.Currency')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cc.Wallet')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('ERROR', 'Error'), ('DONE', 'Done')], default='NEW', max_length=10, verbose_name='State')),
                ('walletconflicts', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Walletconflicts txid')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cc.Wallet'),
        ),
        migrations.AddField(
            model_name='address',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cc.Currency'),
        ),
        migrations.AddField(
            model_name='address',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='cc.Wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Label'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('txid', 'address')},
        ),
        migrations.AddField(
            model_name='currency',
            name='dust',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0000543'), max_digits=18, verbose_name='Dust'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='api_url',
            field=models.CharField(blank=True, default='http://localhost:8332', max_length=100, null=True, verbose_name='API hostname'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='label',
            field=models.CharField(default='Bitcoin', max_length=20, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='magicbyte',
            field=models.CommaSeparatedIntegerField(default='0,5', max_length=10, verbose_name='Magicbytes'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='ticker',
            field=models.CharField(default='BTC', max_length=4, primary_key=True, serialize=False, verbose_name='Ticker'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='magicbyte',
            field=models.CharField(default='0,5', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Magicbytes'),
        ),
    ]
