# Generated by Django 2.0 on 2017-12-18 10:01

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0010_withdrawtransaction_walletconflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='magicbyte',
            field=models.CharField(default='0,5', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Magicbytes'),
        ),
    ]
